package com.br.pokedexagain.ui.util

import androidx.compose.ui.graphics.Color

object PokemonTypeUtils {

    fun getTypeCardBackgroundColor(type: String?): Color {
        return when (type?.lowercase()?.trim()) {
            "grass" -> Color(0xFF48D0B0)
            "fire" -> Color(0xFFFB6C6C)
            "water" -> Color(0xFF76BDFE)
            "bug" -> Color(0xFFA7D87D)
            "electric" -> Color(0xFFFFD86F)
            "normal" -> Color(0xFFC6C6A7)
            "poison" -> Color(0xFFB57EDC)
            "ground" -> Color(0xFFE0C068)
            "rock" -> Color(0xFFC5B078)
            "psychic" -> Color(0xFFFA92B2)
            "ice" -> Color(0xFF98D8D8)
            "dragon" -> Color(0xFF9A70F8)
            "ghost" -> Color(0xFF7558A4)
            "dark" -> Color(0xFF8D7868)
            "steel" -> Color(0xFFB8B8D0)
            "fairy" -> Color(0xFFEE99AC)
            "fighting" -> Color(0xFFD56723)
            "flying" -> Color(0xFFA890F0)
            else -> Color(0xFF90A4AE)
        }
    }

    fun getTypeBadgeBackgroundColor(type: String?): Color {
        return when (type?.lowercase()?.trim()) {
            "grass", "fire", "water", "bug", "electric", "normal",
            "poison", "ground", "rock", "psychic", "ice", "dragon",
            "ghost", "dark", "steel", "fairy", "fighting", "flying" -> Color(0x33000000)
            else -> Color(0x33000000)
        }
    }

    val allTypes = listOf(
        "Grass", "Fire", "Water", "Electric", "Bug", "Poison",
        "Ground", "Rock", "Psychic", "Ice", "Dragon", "Ghost",
        "Normal", "Fighting", "Flying", "Steel", "Fairy", "Dark"
    )

    fun getTypesForPokemon(id: Int): List<String> {
        return typeMap[id] ?: listOf("Normal")
    }

    private val typeMap: Map<Int, List<String>> by lazy {
        buildMap(1025) {
            putAll(getGen1Types())
            putAll(getGen2Types())
            putAll(getGen3Types())
            putAll(getGen4Types())
            putAll(getGen5Types())
            putAll(getGen6Types())
            putAll(getGen7Types())
            putAll(getGen8Types())
            putAll(getGen9Types())
        }
    }

    private fun getGen1Types(): Map<Int, List<String>> = mapOf(
        1 to listOf("Grass", "Poison"),
        2 to listOf("Grass", "Poison"),
        3 to listOf("Grass", "Poison"),
        4 to listOf("Fire"),
        5 to listOf("Fire"),
        6 to listOf("Fire", "Flying"),
        7 to listOf("Water"),
        8 to listOf("Water"),
        9 to listOf("Water"),
        10 to listOf("Bug"),
        11 to listOf("Bug"),
        12 to listOf("Bug", "Flying"),
        13 to listOf("Bug", "Poison"),
        14 to listOf("Bug", "Poison"),
        15 to listOf("Bug", "Poison"),
        16 to listOf("Flying", "Normal"),
        17 to listOf("Flying", "Normal"),
        18 to listOf("Flying", "Normal"),
        19 to listOf("Normal"),
        20 to listOf("Normal"),
        21 to listOf("Flying", "Normal"),
        22 to listOf("Flying", "Normal"),
        23 to listOf("Poison"),
        24 to listOf("Poison"),
        25 to listOf("Electric"),
        26 to listOf("Electric"),
        27 to listOf("Ground"),
        28 to listOf("Ground"),
        29 to listOf("Poison"),
        30 to listOf("Poison"),
        31 to listOf("Ground", "Poison"),
        32 to listOf("Poison"),
        33 to listOf("Poison"),
        34 to listOf("Ground", "Poison"),
        35 to listOf("Fairy"),
        36 to listOf("Fairy"),
        37 to listOf("Fire"),
        38 to listOf("Fire"),
        39 to listOf("Fairy", "Normal"),
        40 to listOf("Fairy", "Normal"),
        41 to listOf("Poison", "Flying"),
        42 to listOf("Poison", "Flying"),
        43 to listOf("Grass", "Poison"),
        44 to listOf("Grass", "Poison"),
        45 to listOf("Grass", "Poison"),
        46 to listOf("Grass", "Bug"),
        47 to listOf("Grass", "Bug"),
        48 to listOf("Bug", "Poison"),
        49 to listOf("Bug", "Poison"),
        50 to listOf("Ground"),
        51 to listOf("Ground"),
        52 to listOf("Normal"),
        53 to listOf("Normal"),
        54 to listOf("Water"),
        55 to listOf("Water"),
        56 to listOf("Fighting"),
        57 to listOf("Fighting"),
        58 to listOf("Fire"),
        59 to listOf("Fire"),
        60 to listOf("Water"),
        61 to listOf("Water"),
        62 to listOf("Water", "Fighting"),
        63 to listOf("Psychic"),
        64 to listOf("Psychic"),
        65 to listOf("Psychic"),
        66 to listOf("Fighting"),
        67 to listOf("Fighting"),
        68 to listOf("Fighting"),
        69 to listOf("Grass", "Poison"),
        70 to listOf("Grass", "Poison"),
        71 to listOf("Grass", "Poison"),
        72 to listOf("Water", "Poison"),
        73 to listOf("Water", "Poison"),
        74 to listOf("Rock", "Ground"),
        75 to listOf("Rock", "Ground"),
        76 to listOf("Rock", "Ground"),
        77 to listOf("Fire"),
        78 to listOf("Fire"),
        79 to listOf("Psychic", "Water"),
        80 to listOf("Psychic", "Water"),
        81 to listOf("Electric", "Steel"),
        82 to listOf("Electric", "Steel"),
        83 to listOf("Flying", "Normal"),
        84 to listOf("Flying", "Normal"),
        85 to listOf("Flying", "Normal"),
        86 to listOf("Water"),
        87 to listOf("Ice", "Water"),
        88 to listOf("Poison"),
        89 to listOf("Poison"),
        90 to listOf("Water"),
        91 to listOf("Ice", "Water"),
        92 to listOf("Ghost", "Poison"),
        93 to listOf("Ghost", "Poison"),
        94 to listOf("Ghost", "Poison"),
        95 to listOf("Rock", "Ground"),
        96 to listOf("Psychic"),
        97 to listOf("Psychic"),
        98 to listOf("Water"),
        99 to listOf("Water"),
        100 to listOf("Electric"),
        101 to listOf("Electric"),
        102 to listOf("Psychic", "Grass"),
        103 to listOf("Psychic", "Grass"),
        104 to listOf("Ground"),
        105 to listOf("Ground"),
        106 to listOf("Fighting"),
        107 to listOf("Fighting"),
        108 to listOf("Normal"),
        109 to listOf("Poison"),
        110 to listOf("Poison"),
        111 to listOf("Rock", "Ground"),
        112 to listOf("Rock", "Ground"),
        113 to listOf("Normal"),
        114 to listOf("Grass"),
        115 to listOf("Normal"),
        116 to listOf("Water"),
        117 to listOf("Water"),
        118 to listOf("Water"),
        119 to listOf("Water"),
        120 to listOf("Water"),
        121 to listOf("Psychic", "Water"),
        122 to listOf("Fairy", "Psychic"),
        123 to listOf("Bug", "Flying"),
        124 to listOf("Ice", "Psychic"),
        125 to listOf("Electric"),
        126 to listOf("Fire"),
        127 to listOf("Bug"),
        128 to listOf("Normal"),
        129 to listOf("Water"),
        130 to listOf("Water", "Flying"),
        131 to listOf("Ice", "Water"),
        132 to listOf("Normal"),
        133 to listOf("Normal"),
        134 to listOf("Water"),
        135 to listOf("Electric"),
        136 to listOf("Fire"),
        137 to listOf("Normal"),
        138 to listOf("Water", "Rock"),
        139 to listOf("Water", "Rock"),
        140 to listOf("Water", "Rock"),
        141 to listOf("Water", "Rock"),
        142 to listOf("Rock", "Flying"),
        143 to listOf("Normal"),
        144 to listOf("Ice", "Flying"),
        145 to listOf("Electric", "Flying"),
        146 to listOf("Fire", "Flying"),
        147 to listOf("Dragon"),
        148 to listOf("Dragon"),
        149 to listOf("Dragon", "Flying"),
        150 to listOf("Psychic"),
        151 to listOf("Psychic")
    )

    private fun getGen2Types(): Map<Int, List<String>> = mapOf(
        152 to listOf("Grass"),
        153 to listOf("Grass"),
        154 to listOf("Grass"),
        155 to listOf("Fire"),
        156 to listOf("Fire"),
        157 to listOf("Fire"),
        158 to listOf("Water"),
        159 to listOf("Water"),
        160 to listOf("Water"),
        161 to listOf("Normal"),
        162 to listOf("Normal"),
        163 to listOf("Flying", "Normal"),
        164 to listOf("Flying", "Normal"),
        165 to listOf("Bug", "Flying"),
        166 to listOf("Bug", "Flying"),
        167 to listOf("Bug", "Poison"),
        168 to listOf("Bug", "Poison"),
        169 to listOf("Poison", "Flying"),
        170 to listOf("Electric", "Water"),
        171 to listOf("Electric", "Water"),
        172 to listOf("Electric"),
        173 to listOf("Fairy"),
        174 to listOf("Fairy", "Normal"),
        175 to listOf("Fairy"),
        176 to listOf("Fairy", "Flying"),
        177 to listOf("Psychic", "Flying"),
        178 to listOf("Psychic", "Flying"),
        179 to listOf("Electric"),
        180 to listOf("Electric"),
        181 to listOf("Electric"),
        182 to listOf("Grass"),
        183 to listOf("Fairy", "Water"),
        184 to listOf("Fairy", "Water"),
        185 to listOf("Rock"),
        186 to listOf("Water"),
        187 to listOf("Grass", "Flying"),
        188 to listOf("Grass", "Flying"),
        189 to listOf("Grass", "Flying"),
        190 to listOf("Normal"),
        191 to listOf("Grass"),
        192 to listOf("Grass"),
        193 to listOf("Bug", "Flying"),
        194 to listOf("Water", "Ground"),
        195 to listOf("Water", "Ground"),
        196 to listOf("Psychic"),
        197 to listOf("Dark"),
        198 to listOf("Dark", "Flying"),
        199 to listOf("Psychic", "Water"),
        200 to listOf("Ghost"),
        201 to listOf("Psychic"),
        202 to listOf("Psychic"),
        203 to listOf("Psychic", "Normal"),
        204 to listOf("Bug"),
        205 to listOf("Steel", "Bug"),
        206 to listOf("Normal"),
        207 to listOf("Ground", "Flying"),
        208 to listOf("Steel", "Ground"),
        209 to listOf("Fairy"),
        210 to listOf("Fairy"),
        211 to listOf("Water", "Poison"),
        212 to listOf("Steel", "Bug"),
        213 to listOf("Bug", "Rock"),
        214 to listOf("Bug", "Fighting"),
        215 to listOf("Dark", "Ice"),
        216 to listOf("Normal"),
        217 to listOf("Normal"),
        218 to listOf("Fire"),
        219 to listOf("Fire", "Rock"),
        220 to listOf("Ice", "Ground"),
        221 to listOf("Ice", "Ground"),
        222 to listOf("Water", "Rock"),
        223 to listOf("Water"),
        224 to listOf("Water"),
        225 to listOf("Ice", "Flying"),
        226 to listOf("Water", "Flying"),
        227 to listOf("Steel", "Flying"),
        228 to listOf("Dark", "Fire"),
        229 to listOf("Dark", "Fire"),
        230 to listOf("Dragon", "Water"),
        231 to listOf("Ground"),
        232 to listOf("Ground"),
        233 to listOf("Normal"),
        234 to listOf("Normal"),
        235 to listOf("Normal"),
        236 to listOf("Fighting"),
        237 to listOf("Fighting"),
        238 to listOf("Ice", "Psychic"),
        239 to listOf("Electric"),
        240 to listOf("Fire"),
        241 to listOf("Normal"),
        242 to listOf("Normal"),
        243 to listOf("Electric"),
        244 to listOf("Fire"),
        245 to listOf("Water"),
        246 to listOf("Rock", "Ground"),
        247 to listOf("Rock", "Ground"),
        248 to listOf("Dark", "Rock"),
        249 to listOf("Psychic", "Flying"),
        250 to listOf("Fire", "Flying"),
        251 to listOf("Psychic", "Grass")
    )

    private fun getGen3Types(): Map<Int, List<String>> = mapOf(
        252 to listOf("Grass"),
        253 to listOf("Grass"),
        254 to listOf("Grass"),
        255 to listOf("Fire"),
        256 to listOf("Fire", "Fighting"),
        257 to listOf("Fire", "Fighting"),
        258 to listOf("Water"),
        259 to listOf("Water", "Ground"),
        260 to listOf("Water", "Ground"),
        261 to listOf("Dark"),
        262 to listOf("Dark"),
        263 to listOf("Normal"),
        264 to listOf("Normal"),
        265 to listOf("Bug"),
        266 to listOf("Bug"),
        267 to listOf("Bug", "Flying"),
        268 to listOf("Bug"),
        269 to listOf("Bug", "Poison"),
        270 to listOf("Grass", "Water"),
        271 to listOf("Grass", "Water"),
        272 to listOf("Grass", "Water"),
        273 to listOf("Grass"),
        274 to listOf("Dark", "Grass"),
        275 to listOf("Dark", "Grass"),
        276 to listOf("Flying", "Normal"),
        277 to listOf("Flying", "Normal"),
        278 to listOf("Water", "Flying"),
        279 to listOf("Water", "Flying"),
        280 to listOf("Fairy", "Psychic"),
        281 to listOf("Fairy", "Psychic"),
        282 to listOf("Fairy", "Psychic"),
        283 to listOf("Water", "Bug"),
        284 to listOf("Bug", "Flying"),
        285 to listOf("Grass"),
        286 to listOf("Grass", "Fighting"),
        287 to listOf("Normal"),
        288 to listOf("Normal"),
        289 to listOf("Normal"),
        290 to listOf("Bug", "Ground"),
        291 to listOf("Bug", "Flying"),
        292 to listOf("Ghost", "Bug"),
        293 to listOf("Normal"),
        294 to listOf("Normal"),
        295 to listOf("Normal"),
        296 to listOf("Fighting"),
        297 to listOf("Fighting"),
        298 to listOf("Fairy", "Normal"),
        299 to listOf("Rock"),
        300 to listOf("Normal"),
        301 to listOf("Normal"),
        302 to listOf("Dark", "Ghost"),
        303 to listOf("Fairy", "Steel"),
        304 to listOf("Steel", "Rock"),
        305 to listOf("Steel", "Rock"),
        306 to listOf("Steel", "Rock"),
        307 to listOf("Psychic", "Fighting"),
        308 to listOf("Psychic", "Fighting"),
        309 to listOf("Electric"),
        310 to listOf("Electric"),
        311 to listOf("Electric"),
        312 to listOf("Electric"),
        313 to listOf("Bug"),
        314 to listOf("Bug"),
        315 to listOf("Grass", "Poison"),
        316 to listOf("Poison"),
        317 to listOf("Poison"),
        318 to listOf("Dark", "Water"),
        319 to listOf("Dark", "Water"),
        320 to listOf("Water"),
        321 to listOf("Water"),
        322 to listOf("Fire", "Ground"),
        323 to listOf("Fire", "Ground"),
        324 to listOf("Fire"),
        325 to listOf("Psychic"),
        326 to listOf("Psychic"),
        327 to listOf("Normal"),
        328 to listOf("Ground"),
        329 to listOf("Dragon", "Ground"),
        330 to listOf("Dragon", "Ground"),
        331 to listOf("Grass"),
        332 to listOf("Dark", "Grass"),
        333 to listOf("Flying", "Normal"),
        334 to listOf("Dragon", "Flying"),
        335 to listOf("Normal"),
        336 to listOf("Poison"),
        337 to listOf("Psychic", "Rock"),
        338 to listOf("Psychic", "Rock"),
        339 to listOf("Water", "Ground"),
        340 to listOf("Water", "Ground"),
        341 to listOf("Water"),
        342 to listOf("Dark", "Water"),
        343 to listOf("Psychic", "Ground"),
        344 to listOf("Psychic", "Ground"),
        345 to listOf("Grass", "Rock"),
        346 to listOf("Grass", "Rock"),
        347 to listOf("Bug", "Rock"),
        348 to listOf("Bug", "Rock"),
        349 to listOf("Water"),
        350 to listOf("Water"),
        351 to listOf("Normal"),
        352 to listOf("Normal"),
        353 to listOf("Ghost"),
        354 to listOf("Ghost"),
        355 to listOf("Ghost"),
        356 to listOf("Ghost"),
        357 to listOf("Grass", "Flying"),
        358 to listOf("Psychic"),
        359 to listOf("Dark"),
        360 to listOf("Psychic"),
        361 to listOf("Ice"),
        362 to listOf("Ice"),
        363 to listOf("Ice", "Water"),
        364 to listOf("Ice", "Water"),
        365 to listOf("Ice", "Water"),
        366 to listOf("Water"),
        367 to listOf("Water"),
        368 to listOf("Water"),
        369 to listOf("Water", "Rock"),
        370 to listOf("Water"),
        371 to listOf("Dragon"),
        372 to listOf("Dragon"),
        373 to listOf("Dragon", "Flying"),
        374 to listOf("Psychic", "Steel"),
        375 to listOf("Psychic", "Steel"),
        376 to listOf("Psychic", "Steel"),
        377 to listOf("Rock"),
        378 to listOf("Ice"),
        379 to listOf("Steel"),
        380 to listOf("Dragon", "Psychic"),
        381 to listOf("Dragon", "Psychic"),
        382 to listOf("Water"),
        383 to listOf("Ground"),
        384 to listOf("Dragon", "Flying"),
        385 to listOf("Psychic", "Steel"),
        386 to listOf("Psychic")
    )

    private fun getGen4Types(): Map<Int, List<String>> = mapOf(
        387 to listOf("Grass"),
        388 to listOf("Grass"),
        389 to listOf("Grass", "Ground"),
        390 to listOf("Fire"),
        391 to listOf("Fire", "Fighting"),
        392 to listOf("Fire", "Fighting"),
        393 to listOf("Water"),
        394 to listOf("Water"),
        395 to listOf("Water", "Steel"),
        396 to listOf("Flying", "Normal"),
        397 to listOf("Flying", "Normal"),
        398 to listOf("Flying", "Normal"),
        399 to listOf("Normal"),
        400 to listOf("Water", "Normal"),
        401 to listOf("Bug"),
        402 to listOf("Bug"),
        403 to listOf("Electric"),
        404 to listOf("Electric"),
        405 to listOf("Electric"),
        406 to listOf("Grass", "Poison"),
        407 to listOf("Grass", "Poison"),
        408 to listOf("Rock"),
        409 to listOf("Rock"),
        410 to listOf("Steel", "Rock"),
        411 to listOf("Steel", "Rock"),
        412 to listOf("Bug"),
        413 to listOf("Grass", "Bug"),
        414 to listOf("Bug", "Flying"),
        415 to listOf("Bug", "Flying"),
        416 to listOf("Bug", "Flying"),
        417 to listOf("Electric"),
        418 to listOf("Water"),
        419 to listOf("Water"),
        420 to listOf("Grass"),
        421 to listOf("Grass"),
        422 to listOf("Water"),
        423 to listOf("Water", "Ground"),
        424 to listOf("Normal"),
        425 to listOf("Ghost", "Flying"),
        426 to listOf("Ghost", "Flying"),
        427 to listOf("Normal"),
        428 to listOf("Normal"),
        429 to listOf("Ghost"),
        430 to listOf("Dark", "Flying"),
        431 to listOf("Normal"),
        432 to listOf("Normal"),
        433 to listOf("Psychic"),
        434 to listOf("Dark", "Poison"),
        435 to listOf("Dark", "Poison"),
        436 to listOf("Psychic", "Steel"),
        437 to listOf("Psychic", "Steel"),
        438 to listOf("Rock"),
        439 to listOf("Fairy", "Psychic"),
        440 to listOf("Normal"),
        441 to listOf("Flying", "Normal"),
        442 to listOf("Dark", "Ghost"),
        443 to listOf("Dragon", "Ground"),
        444 to listOf("Dragon", "Ground"),
        445 to listOf("Dragon", "Ground"),
        446 to listOf("Normal"),
        447 to listOf("Fighting"),
        448 to listOf("Steel", "Fighting"),
        449 to listOf("Ground"),
        450 to listOf("Ground"),
        451 to listOf("Bug", "Poison"),
        452 to listOf("Dark", "Poison"),
        453 to listOf("Poison", "Fighting"),
        454 to listOf("Poison", "Fighting"),
        455 to listOf("Grass"),
        456 to listOf("Water"),
        457 to listOf("Water"),
        458 to listOf("Water", "Flying"),
        459 to listOf("Ice", "Grass"),
        460 to listOf("Ice", "Grass"),
        461 to listOf("Dark", "Ice"),
        462 to listOf("Electric", "Steel"),
        463 to listOf("Normal"),
        464 to listOf("Rock", "Ground"),
        465 to listOf("Grass"),
        466 to listOf("Electric"),
        467 to listOf("Fire"),
        468 to listOf("Fairy", "Flying"),
        469 to listOf("Bug", "Flying"),
        470 to listOf("Grass"),
        471 to listOf("Ice"),
        472 to listOf("Ground", "Flying"),
        473 to listOf("Ice", "Ground"),
        474 to listOf("Normal"),
        475 to listOf("Psychic", "Fighting"),
        476 to listOf("Steel", "Rock"),
        477 to listOf("Ghost"),
        478 to listOf("Ice", "Ghost"),
        479 to listOf("Electric", "Ghost"),
        480 to listOf("Psychic"),
        481 to listOf("Psychic"),
        482 to listOf("Psychic"),
        483 to listOf("Dragon", "Steel"),
        484 to listOf("Dragon", "Water"),
        485 to listOf("Fire", "Steel"),
        486 to listOf("Normal"),
        487 to listOf("Dragon", "Ghost"),
        488 to listOf("Psychic"),
        489 to listOf("Water"),
        490 to listOf("Water"),
        491 to listOf("Dark"),
        492 to listOf("Grass"),
        493 to listOf("Normal")
    )

    private fun getGen5Types(): Map<Int, List<String>> = mapOf(
        494 to listOf("Psychic", "Fire"),
        495 to listOf("Grass"),
        496 to listOf("Grass"),
        497 to listOf("Grass"),
        498 to listOf("Fire"),
        499 to listOf("Fire", "Fighting"),
        500 to listOf("Fire", "Fighting"),
        501 to listOf("Water"),
        502 to listOf("Water"),
        503 to listOf("Water"),
        504 to listOf("Normal"),
        505 to listOf("Normal"),
        506 to listOf("Normal"),
        507 to listOf("Normal"),
        508 to listOf("Normal"),
        509 to listOf("Dark"),
        510 to listOf("Dark"),
        511 to listOf("Grass"),
        512 to listOf("Grass"),
        513 to listOf("Fire"),
        514 to listOf("Fire"),
        515 to listOf("Water"),
        516 to listOf("Water"),
        517 to listOf("Psychic"),
        518 to listOf("Psychic"),
        519 to listOf("Flying", "Normal"),
        520 to listOf("Flying", "Normal"),
        521 to listOf("Flying", "Normal"),
        522 to listOf("Electric"),
        523 to listOf("Electric"),
        524 to listOf("Rock"),
        525 to listOf("Rock"),
        526 to listOf("Rock"),
        527 to listOf("Psychic", "Flying"),
        528 to listOf("Psychic", "Flying"),
        529 to listOf("Ground"),
        530 to listOf("Steel", "Ground"),
        531 to listOf("Normal"),
        532 to listOf("Fighting"),
        533 to listOf("Fighting"),
        534 to listOf("Fighting"),
        535 to listOf("Water"),
        536 to listOf("Water", "Ground"),
        537 to listOf("Water", "Ground"),
        538 to listOf("Fighting"),
        539 to listOf("Fighting"),
        540 to listOf("Grass", "Bug"),
        541 to listOf("Grass", "Bug"),
        542 to listOf("Grass", "Bug"),
        543 to listOf("Bug", "Poison"),
        544 to listOf("Bug", "Poison"),
        545 to listOf("Bug", "Poison"),
        546 to listOf("Fairy", "Grass"),
        547 to listOf("Fairy", "Grass"),
        548 to listOf("Grass"),
        549 to listOf("Grass"),
        550 to listOf("Water"),
        551 to listOf("Dark", "Ground"),
        552 to listOf("Dark", "Ground"),
        553 to listOf("Dark", "Ground"),
        554 to listOf("Fire"),
        555 to listOf("Fire"),
        556 to listOf("Grass"),
        557 to listOf("Bug", "Rock"),
        558 to listOf("Bug", "Rock"),
        559 to listOf("Dark", "Fighting"),
        560 to listOf("Dark", "Fighting"),
        561 to listOf("Psychic", "Flying"),
        562 to listOf("Ghost"),
        563 to listOf("Ghost"),
        564 to listOf("Water", "Rock"),
        565 to listOf("Water", "Rock"),
        566 to listOf("Rock", "Flying"),
        567 to listOf("Rock", "Flying"),
        568 to listOf("Poison"),
        569 to listOf("Poison"),
        570 to listOf("Dark"),
        571 to listOf("Dark"),
        572 to listOf("Normal"),
        573 to listOf("Normal"),
        574 to listOf("Psychic"),
        575 to listOf("Psychic"),
        576 to listOf("Psychic"),
        577 to listOf("Psychic"),
        578 to listOf("Psychic"),
        579 to listOf("Psychic"),
        580 to listOf("Water", "Flying"),
        581 to listOf("Water", "Flying"),
        582 to listOf("Ice"),
        583 to listOf("Ice"),
        584 to listOf("Ice"),
        585 to listOf("Grass", "Normal"),
        586 to listOf("Grass", "Normal"),
        587 to listOf("Electric", "Flying"),
        588 to listOf("Bug"),
        589 to listOf("Steel", "Bug"),
        590 to listOf("Grass", "Poison"),
        591 to listOf("Grass", "Poison"),
        592 to listOf("Water", "Ghost"),
        593 to listOf("Water", "Ghost"),
        594 to listOf("Water"),
        595 to listOf("Electric", "Bug"),
        596 to listOf("Electric", "Bug"),
        597 to listOf("Grass", "Steel"),
        598 to listOf("Grass", "Steel"),
        599 to listOf("Steel"),
        600 to listOf("Steel"),
        601 to listOf("Steel"),
        602 to listOf("Electric"),
        603 to listOf("Electric"),
        604 to listOf("Electric"),
        605 to listOf("Psychic"),
        606 to listOf("Psychic"),
        607 to listOf("Fire", "Ghost"),
        608 to listOf("Fire", "Ghost"),
        609 to listOf("Fire", "Ghost"),
        610 to listOf("Dragon"),
        611 to listOf("Dragon"),
        612 to listOf("Dragon"),
        613 to listOf("Ice"),
        614 to listOf("Ice"),
        615 to listOf("Ice"),
        616 to listOf("Bug"),
        617 to listOf("Bug"),
        618 to listOf("Electric", "Ground"),
        619 to listOf("Fighting"),
        620 to listOf("Fighting"),
        621 to listOf("Dragon"),
        622 to listOf("Ghost", "Ground"),
        623 to listOf("Ghost", "Ground"),
        624 to listOf("Dark", "Steel"),
        625 to listOf("Dark", "Steel"),
        626 to listOf("Normal"),
        627 to listOf("Flying", "Normal"),
        628 to listOf("Flying", "Normal"),
        629 to listOf("Dark", "Flying"),
        630 to listOf("Dark", "Flying"),
        631 to listOf("Fire"),
        632 to listOf("Steel", "Bug"),
        633 to listOf("Dark", "Dragon"),
        634 to listOf("Dark", "Dragon"),
        635 to listOf("Dark", "Dragon"),
        636 to listOf("Fire", "Bug"),
        637 to listOf("Fire", "Bug"),
        638 to listOf("Steel", "Fighting"),
        639 to listOf("Rock", "Fighting"),
        640 to listOf("Grass", "Fighting"),
        641 to listOf("Flying"),
        642 to listOf("Electric", "Flying"),
        643 to listOf("Dragon", "Fire"),
        644 to listOf("Dragon", "Electric"),
        645 to listOf("Ground", "Flying"),
        646 to listOf("Dragon", "Ice"),
        647 to listOf("Water", "Fighting"),
        648 to listOf("Psychic", "Normal"),
        649 to listOf("Steel", "Bug")
    )

    private fun getGen6Types(): Map<Int, List<String>> = mapOf(
        650 to listOf("Grass"),
        651 to listOf("Grass"),
        652 to listOf("Grass", "Fighting"),
        653 to listOf("Fire"),
        654 to listOf("Fire"),
        655 to listOf("Psychic", "Fire"),
        656 to listOf("Water"),
        657 to listOf("Water"),
        658 to listOf("Dark", "Water"),
        659 to listOf("Normal"),
        660 to listOf("Ground", "Normal"),
        661 to listOf("Flying", "Normal"),
        662 to listOf("Fire", "Flying"),
        663 to listOf("Fire", "Flying"),
        664 to listOf("Bug"),
        665 to listOf("Bug"),
        666 to listOf("Bug", "Flying"),
        667 to listOf("Fire", "Normal"),
        668 to listOf("Fire", "Normal"),
        669 to listOf("Fairy"),
        670 to listOf("Fairy"),
        671 to listOf("Fairy"),
        672 to listOf("Grass"),
        673 to listOf("Grass"),
        674 to listOf("Fighting"),
        675 to listOf("Dark", "Fighting"),
        676 to listOf("Normal"),
        677 to listOf("Psychic"),
        678 to listOf("Psychic"),
        679 to listOf("Steel", "Ghost"),
        680 to listOf("Steel", "Ghost"),
        681 to listOf("Steel", "Ghost"),
        682 to listOf("Fairy"),
        683 to listOf("Fairy"),
        684 to listOf("Fairy"),
        685 to listOf("Fairy"),
        686 to listOf("Dark", "Psychic"),
        687 to listOf("Dark", "Psychic"),
        688 to listOf("Water", "Rock"),
        689 to listOf("Water", "Rock"),
        690 to listOf("Water", "Poison"),
        691 to listOf("Dragon", "Poison"),
        692 to listOf("Water"),
        693 to listOf("Water"),
        694 to listOf("Electric", "Normal"),
        695 to listOf("Electric", "Normal"),
        696 to listOf("Dragon", "Rock"),
        697 to listOf("Dragon", "Rock"),
        698 to listOf("Ice", "Rock"),
        699 to listOf("Ice", "Rock"),
        700 to listOf("Fairy"),
        701 to listOf("Flying", "Fighting"),
        702 to listOf("Fairy", "Electric"),
        703 to listOf("Fairy", "Rock"),
        704 to listOf("Dragon"),
        705 to listOf("Dragon"),
        706 to listOf("Dragon"),
        707 to listOf("Fairy", "Steel"),
        708 to listOf("Grass", "Ghost"),
        709 to listOf("Grass", "Ghost"),
        710 to listOf("Grass", "Ghost"),
        711 to listOf("Grass", "Ghost"),
        712 to listOf("Ice"),
        713 to listOf("Ice"),
        714 to listOf("Dragon", "Flying"),
        715 to listOf("Dragon", "Flying"),
        716 to listOf("Fairy"),
        717 to listOf("Dark", "Flying"),
        718 to listOf("Dragon", "Ground"),
        719 to listOf("Fairy", "Rock"),
        720 to listOf("Psychic", "Ghost"),
        721 to listOf("Water", "Fire")
    )

    private fun getGen7Types(): Map<Int, List<String>> = mapOf(
        722 to listOf("Grass", "Flying"),
        723 to listOf("Grass", "Flying"),
        724 to listOf("Grass", "Ghost"),
        725 to listOf("Fire"),
        726 to listOf("Fire"),
        727 to listOf("Dark", "Fire"),
        728 to listOf("Water"),
        729 to listOf("Water"),
        730 to listOf("Fairy", "Water"),
        731 to listOf("Flying", "Normal"),
        732 to listOf("Flying", "Normal"),
        733 to listOf("Flying", "Normal"),
        734 to listOf("Normal"),
        735 to listOf("Normal"),
        736 to listOf("Bug"),
        737 to listOf("Electric", "Bug"),
        738 to listOf("Electric", "Bug"),
        739 to listOf("Fighting"),
        740 to listOf("Ice", "Fighting"),
        741 to listOf("Fire", "Flying"),
        742 to listOf("Fairy", "Bug"),
        743 to listOf("Fairy", "Bug"),
        744 to listOf("Rock"),
        745 to listOf("Rock"),
        746 to listOf("Water"),
        747 to listOf("Water", "Poison"),
        748 to listOf("Water", "Poison"),
        749 to listOf("Ground"),
        750 to listOf("Ground"),
        751 to listOf("Water", "Bug"),
        752 to listOf("Water", "Bug"),
        753 to listOf("Grass"),
        754 to listOf("Grass"),
        755 to listOf("Fairy", "Grass"),
        756 to listOf("Fairy", "Grass"),
        757 to listOf("Fire", "Poison"),
        758 to listOf("Fire", "Poison"),
        759 to listOf("Fighting", "Normal"),
        760 to listOf("Fighting", "Normal"),
        761 to listOf("Grass"),
        762 to listOf("Grass"),
        763 to listOf("Grass"),
        764 to listOf("Fairy"),
        765 to listOf("Psychic", "Normal"),
        766 to listOf("Fighting"),
        767 to listOf("Water", "Bug"),
        768 to listOf("Water", "Bug"),
        769 to listOf("Ghost", "Ground"),
        770 to listOf("Ghost", "Ground"),
        771 to listOf("Water"),
        772 to listOf("Normal"),
        773 to listOf("Normal"),
        774 to listOf("Rock", "Flying"),
        775 to listOf("Normal"),
        776 to listOf("Dragon", "Fire"),
        777 to listOf("Electric", "Steel"),
        778 to listOf("Fairy", "Ghost"),
        779 to listOf("Psychic", "Water"),
        780 to listOf("Dragon", "Normal"),
        781 to listOf("Grass", "Ghost"),
        782 to listOf("Dragon"),
        783 to listOf("Dragon", "Fighting"),
        784 to listOf("Dragon", "Fighting"),
        785 to listOf("Fairy", "Electric"),
        786 to listOf("Fairy", "Psychic"),
        787 to listOf("Fairy", "Grass"),
        788 to listOf("Fairy", "Water"),
        789 to listOf("Psychic"),
        790 to listOf("Psychic"),
        791 to listOf("Psychic", "Steel"),
        792 to listOf("Psychic", "Ghost"),
        793 to listOf("Rock", "Poison"),
        794 to listOf("Bug", "Fighting"),
        795 to listOf("Bug", "Fighting"),
        796 to listOf("Electric"),
        797 to listOf("Steel", "Flying"),
        798 to listOf("Grass", "Steel"),
        799 to listOf("Dark", "Dragon"),
        800 to listOf("Psychic"),
        801 to listOf("Fairy", "Steel"),
        802 to listOf("Ghost", "Fighting"),
        803 to listOf("Poison"),
        804 to listOf("Dragon", "Poison"),
        805 to listOf("Steel", "Rock"),
        806 to listOf("Fire", "Ghost"),
        807 to listOf("Electric"),
        808 to listOf("Steel"),
        809 to listOf("Steel")
    )

    private fun getGen8Types(): Map<Int, List<String>> = mapOf(
        810 to listOf("Grass"),
        811 to listOf("Grass"),
        812 to listOf("Grass"),
        813 to listOf("Fire"),
        814 to listOf("Fire"),
        815 to listOf("Fire"),
        816 to listOf("Water"),
        817 to listOf("Water"),
        818 to listOf("Water"),
        819 to listOf("Normal"),
        820 to listOf("Normal"),
        821 to listOf("Flying"),
        822 to listOf("Flying"),
        823 to listOf("Steel", "Flying"),
        824 to listOf("Bug"),
        825 to listOf("Psychic", "Bug"),
        826 to listOf("Psychic", "Bug"),
        827 to listOf("Dark"),
        828 to listOf("Dark"),
        829 to listOf("Grass"),
        830 to listOf("Grass"),
        831 to listOf("Normal"),
        832 to listOf("Normal"),
        833 to listOf("Water"),
        834 to listOf("Water", "Rock"),
        835 to listOf("Electric"),
        836 to listOf("Electric"),
        837 to listOf("Rock"),
        838 to listOf("Fire", "Rock"),
        839 to listOf("Fire", "Rock"),
        840 to listOf("Dragon", "Grass"),
        841 to listOf("Dragon", "Grass"),
        842 to listOf("Dragon", "Grass"),
        843 to listOf("Ground"),
        844 to listOf("Ground"),
        845 to listOf("Water", "Flying"),
        846 to listOf("Water"),
        847 to listOf("Water"),
        848 to listOf("Electric", "Poison"),
        849 to listOf("Electric", "Poison"),
        850 to listOf("Fire", "Bug"),
        851 to listOf("Fire", "Bug"),
        852 to listOf("Fighting"),
        853 to listOf("Fighting"),
        854 to listOf("Ghost"),
        855 to listOf("Ghost"),
        856 to listOf("Psychic"),
        857 to listOf("Psychic"),
        858 to listOf("Fairy", "Psychic"),
        859 to listOf("Fairy", "Dark"),
        860 to listOf("Fairy", "Dark"),
        861 to listOf("Fairy", "Dark"),
        862 to listOf("Dark", "Normal"),
        863 to listOf("Steel"),
        864 to listOf("Ghost"),
        865 to listOf("Fighting"),
        866 to listOf("Ice", "Psychic"),
        867 to listOf("Ghost", "Ground"),
        868 to listOf("Fairy"),
        869 to listOf("Fairy"),
        870 to listOf("Fighting"),
        871 to listOf("Electric"),
        872 to listOf("Ice", "Bug"),
        873 to listOf("Ice", "Bug"),
        874 to listOf("Rock"),
        875 to listOf("Ice"),
        876 to listOf("Psychic", "Normal"),
        877 to listOf("Dark", "Electric"),
        878 to listOf("Steel"),
        879 to listOf("Steel"),
        880 to listOf("Dragon", "Electric"),
        881 to listOf("Ice", "Electric"),
        882 to listOf("Dragon", "Water"),
        883 to listOf("Ice", "Water"),
        884 to listOf("Dragon", "Steel"),
        885 to listOf("Dragon", "Ghost"),
        886 to listOf("Dragon", "Ghost"),
        887 to listOf("Dragon", "Ghost"),
        888 to listOf("Fairy"),
        889 to listOf("Fighting"),
        890 to listOf("Dragon", "Poison"),
        891 to listOf("Fighting"),
        892 to listOf("Dark", "Fighting"),
        893 to listOf("Dark", "Grass"),
        894 to listOf("Electric"),
        895 to listOf("Dragon"),
        896 to listOf("Ice"),
        897 to listOf("Ghost"),
        898 to listOf("Psychic", "Grass"),
        899 to listOf("Psychic", "Normal"),
        900 to listOf("Bug", "Rock"),
        901 to listOf("Ground", "Normal"),
        902 to listOf("Water", "Ghost"),
        903 to listOf("Poison", "Fighting"),
        904 to listOf("Dark", "Poison"),
        905 to listOf("Fairy", "Flying")
    )

    private fun getGen9Types(): Map<Int, List<String>> = mapOf(
        906 to listOf("Grass"),
        907 to listOf("Grass"),
        908 to listOf("Dark", "Grass"),
        909 to listOf("Fire"),
        910 to listOf("Fire"),
        911 to listOf("Fire", "Ghost"),
        912 to listOf("Water"),
        913 to listOf("Water"),
        914 to listOf("Water", "Fighting"),
        915 to listOf("Normal"),
        916 to listOf("Normal"),
        917 to listOf("Bug"),
        918 to listOf("Bug"),
        919 to listOf("Bug"),
        920 to listOf("Dark", "Bug"),
        921 to listOf("Electric"),
        922 to listOf("Electric", "Fighting"),
        923 to listOf("Electric", "Fighting"),
        924 to listOf("Normal"),
        925 to listOf("Normal"),
        926 to listOf("Fairy"),
        927 to listOf("Fairy"),
        928 to listOf("Grass", "Normal"),
        929 to listOf("Grass", "Normal"),
        930 to listOf("Grass", "Normal"),
        931 to listOf("Flying", "Normal"),
        932 to listOf("Rock"),
        933 to listOf("Rock"),
        934 to listOf("Rock"),
        935 to listOf("Fire"),
        936 to listOf("Psychic", "Fire"),
        937 to listOf("Fire", "Ghost"),
        938 to listOf("Electric"),
        939 to listOf("Electric"),
        940 to listOf("Electric", "Flying"),
        941 to listOf("Electric", "Flying"),
        942 to listOf("Dark"),
        943 to listOf("Dark"),
        944 to listOf("Poison", "Normal"),
        945 to listOf("Poison", "Normal"),
        946 to listOf("Grass", "Ghost"),
        947 to listOf("Grass", "Ghost"),
        948 to listOf("Grass", "Ground"),
        949 to listOf("Grass", "Ground"),
        950 to listOf("Rock"),
        951 to listOf("Grass"),
        952 to listOf("Grass", "Fire"),
        953 to listOf("Bug"),
        954 to listOf("Psychic", "Bug"),
        955 to listOf("Psychic"),
        956 to listOf("Psychic"),
        957 to listOf("Fairy", "Steel"),
        958 to listOf("Fairy", "Steel"),
        959 to listOf("Fairy", "Steel"),
        960 to listOf("Water"),
        961 to listOf("Water"),
        962 to listOf("Dark", "Flying"),
        963 to listOf("Water"),
        964 to listOf("Water"),
        965 to listOf("Steel", "Poison"),
        966 to listOf("Steel", "Poison"),
        967 to listOf("Dragon", "Normal"),
        968 to listOf("Steel"),
        969 to listOf("Rock", "Poison"),
        970 to listOf("Rock", "Poison"),
        971 to listOf("Ghost"),
        972 to listOf("Ghost"),
        973 to listOf("Flying", "Fighting"),
        974 to listOf("Ice"),
        975 to listOf("Ice"),
        976 to listOf("Psychic", "Water"),
        977 to listOf("Water"),
        978 to listOf("Dragon", "Water"),
        979 to listOf("Ghost", "Fighting"),
        980 to listOf("Ground", "Poison"),
        981 to listOf("Psychic", "Normal"),
        982 to listOf("Normal"),
        983 to listOf("Dark", "Steel"),
        984 to listOf("Ground", "Fighting"),
        985 to listOf("Fairy", "Psychic"),
        986 to listOf("Dark", "Grass"),
        987 to listOf("Fairy", "Ghost"),
        988 to listOf("Bug", "Fighting"),
        989 to listOf("Electric", "Ground"),
        990 to listOf("Steel", "Ground"),
        991 to listOf("Ice", "Water"),
        992 to listOf("Electric", "Fighting"),
        993 to listOf("Dark", "Flying"),
        994 to listOf("Fire", "Poison"),
        995 to listOf("Electric", "Rock"),
        996 to listOf("Dragon", "Ice"),
        997 to listOf("Dragon", "Ice"),
        998 to listOf("Dragon", "Ice"),
        999 to listOf("Ghost"),
        1000 to listOf("Steel", "Ghost"),
        1001 to listOf("Dark", "Grass"),
        1002 to listOf("Dark", "Ice"),
        1003 to listOf("Dark", "Ground"),
        1004 to listOf("Dark", "Fire"),
        1005 to listOf("Dark", "Dragon"),
        1006 to listOf("Fairy", "Fighting"),
        1007 to listOf("Dragon", "Fighting"),
        1008 to listOf("Dragon", "Electric"),
        1009 to listOf("Dragon", "Water"),
        1010 to listOf("Psychic", "Grass"),
        1011 to listOf("Dragon", "Grass"),
        1012 to listOf("Grass", "Ghost"),
        1013 to listOf("Grass", "Ghost"),
        1014 to listOf("Poison", "Fighting"),
        1015 to listOf("Psychic", "Poison"),
        1016 to listOf("Fairy", "Poison"),
        1017 to listOf("Grass"),
        1018 to listOf("Dragon", "Steel"),
        1019 to listOf("Dragon", "Grass"),
        1020 to listOf("Dragon", "Fire"),
        1021 to listOf("Dragon", "Electric"),
        1022 to listOf("Psychic", "Rock"),
        1023 to listOf("Psychic", "Steel"),
        1024 to listOf("Normal"),
        1025 to listOf("Ghost", "Poison")
    )

}
